[package]
name = "sentry-tide"
version = "0.1.0"
authors = ["Kangwook Lee <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
sentry-core = { version = "0.23", default-features = false, features = ["client"] }
tide = { version = "0.16", default-features = false }
